### ISSUE TITLE
Make `DELETE` followed by `ADD` not lose information

### ISSUE THREAD

**Issue by dolhuis** [Amsterdam/GOB-Upload#6]
When an entity is `DELETED` and later, with the same `id` it is `ADD`-ed, with different field values, the old values will be overwritten, thus preventing a correct roll-back of an event.

Ofcourse the history is still present, but the events don't hold the information in themselves to roll them back.

There is a conceptual difference between an initial `ADD` (creating a record, setting attribute values). And a ADD calculated to a previously `DELETED` entity (setting `_date_deleted` to `None` and setting attribute values).

**Comment by dolhuis** [comment]
A delete event could also contain the deleted attribute values, so that when rolling back the `ADD` the attribute values can be reapplied.

**Comment by dolhuis** [comment]
And whereto setting the `_date_deleted` when rolling back an `ADD`?

**Comment by dolhuis** [comment]
Ah. That's a generic problem with roll-backs: as long as we don't the old_value/new_value of control-values like `_data_*`-fields, rolling those back will be hard

**Comment by dolhuis** [comment]
And when we introduce a UUID(?) or hash or something for a specific version of an entity then the conceptual difference between an initial `ADD` and the `ADD` after a `DELETED` is clear. Because then the difference is clear: an initial `ADD` is compared to None, while else it is compared to an existing version.

**Comment by Vegter** [comment]
Basically this is about optimization.

The status of any entty is the sum of it's events.
Each entity should contain a link to the last event that has "touched" the entity (add, change, delete or confirm).
This link can be seen as a kind of UUID, it uniquely identifies the state of the entity.

Each event contains a link to the previous event that touched the entity.
From an entity one can so recover all events that have lead to it's current state.

Undo an event means that the last event that touched the entity is unlinked from the entity.
The event itself is marked as undone so becoming a no-op event.
But the event is still visible. each undo will be kept and can be reported.

The next step is to reconstruct the entity to the previous state.
This is simply done by collecting all events that lead to the current state of the entity.
This is a straightforward action as all events are linked.
The entity can then be deleted and all events can be applied to reconstruct the entity.

The undo event is still in the events list but no longer part of the chain that lead to the current state.

Optimisation (eg intermediate snapshots) can be used to speed up the undo's.
The procedure is however very straightforward and simple.
